name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest

    container: ps2dev/ps2dev:v1.0
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base p7zip
    
    - name: Compile project
      run: |
        make clean packed DUMMY_LIBC_INIT=1
        echo PACKING...
        7z a -t7z "${{ github.event.repository.name }}.7z" hello.elf compressed.elf

      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            ${{ github.event.repository.name }}.7z
